### ISSUE TITLE
dont_remove config option doesn't appear to work

### ISSUE THREAD

**Issue by rockymeza** [colinta/StrangeCase#3]
I have a `deploy_path` of `_site`.  I have files in `_site/static` that I want StrangeCase to ignore.

I tried several things:

``` yaml
dont_remove: ['static.*']
dont_remove: ['_site/static.*']
dont_remove: ['static/*'] # I realized you are using `fnmatch` and not regex as the documentation might suggest
dont_remove: ['_site/static/*']
```

The only one that works is this:

``` yaml
dont_remove: ['*_site/static/*']
```

However, StrangeCase still attempts to delete the directory, which results in a failure.
